version: '3.7'
services:
  test-app:
    build:
      context: ..
      dockerfile: test-env/Dockerfile-app
    command: test-env/run-tests.sh
    volumes:
      - yarn-cache:/usr/local/share/.cache/yarn

volumes:
  yarn-cache:
    external: true
